FROM eclipse-temurin:21-jdk

WORKDIR /rococo
ENV TZ=Europe/Moscow
COPY ./gradle ./gradle
COPY ./rococo-e2e ./rococo-e2e
COPY ./rococo-grpc-common ./rococo-grpc-common
COPY ./gradlew ./
COPY ./build.gradle ./
COPY ./settings.gradle ./
COPY ./gradle.properties ./

ENV BROWSER=chrome
CMD ./gradlew test -Dtest.env=docker -Duser.timezone=Europe/Moscow -Dbrowser=${BROWSER}
