server:
  port: 8080

spring:
  grpc:
    server:
      reflection:
        enabled: false
  application:
    name: rococo-gateway
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    io.grpc: DEBUG
    org.springframework.grpc: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8080'

grpc:
  client:
    rococo-artist:
      address: static://127.0.0.1:8091
      negotiationType: PLAINTEXT
    rococo-country:
      address: static://127.0.0.1:8092
      negotiationType: PLAINTEXT
    rococo-museum:
      address: static://127.0.0.1:8093
      negotiationType: PLAINTEXT
    rococo-painting:
      address: static://127.0.0.1:8094
      negotiationType: PLAINTEXT
    rococo-userdata:
      address: static://127.0.0.1:8089
      negotiationType: PLAINTEXT

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

rococo-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-gateway:
  base-uri: 'http://gateway.rococo.dc:8080'

grpc:
  client:
    rococo-artist:
      address: static://artist.rococo.dc:8091
      negotiationType: PLAINTEXT
    rococo-country:
      address: static://country.rococo.dc:8092
      negotiationType: PLAINTEXT
    rococo-museum:
      address: static://museum.rococo.dc:8093
      negotiationType: PLAINTEXT
    rococo-painting:
      address: static://painting.rococo.dc:8094
      negotiationType: PLAINTEXT
    rococo-userdata:
      address: static://userdata.rococo.dc:8089
      negotiationType: PLAINTEXT