server:
  port: -1

spring:
  grpc:
    server:
      port: 8094
      max-inbound-message-size: 10MB
      servlet:
        enabled: false
  application:
    name: rococo-painting
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/rococo-painting
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    io.grpc: DEBUG
    org.springframework.grpc: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret


---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:mysql://rococo-all-db:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret
