server:
  port: -1

spring:
  grpc:
    server:
      port: 8092
      servlet:
        enabled: false
  application:
    name: rococo-country
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/rococo-country?serverTimezone=UTC&createDatabaseIfNotExist=true'
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: root
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/rococo-country
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    io.grpc: DEBUG
    org.springframework.grpc: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

rococo-country:
  base-uri: 'http://127.0.0.1:8092'

