CREATE DATABASE IF NOT EXISTS `rococo-auth`;
CREATE DATABASE IF NOT EXISTS `rococo-userdata`;
CREATE DATABASE IF NOT EXISTS `rococo-artist`;
CREATE DATABASE IF NOT EXISTS `rococo-country`;
CREATE DATABASE IF NOT EXISTS `rococo-museum`;
CREATE DATABASE IF NOT EXISTS `rococo-painting`;